name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "feature/*"
  
env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPGISTRY }}:test-22.04-v0.31.1
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPGISTRY }}:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run \
          --interactive \
          --tty \
          --rm \
          ${{ env.TEST_TAG }} \
          --volume ./project-demo:/project
          ceedling test:all
      #       - name: Build and push
      #         uses: docker/build-push-action@v5.1.0
      #         with:
      #           context: .
      #           file: Dockerfile.ubuntu
      #           platforms: linux/amd64
      #           push: false
      #           tags: ${{ env.LATEST_TAG }}
