#/.github/workflows/ci.yaml
---
name: CI

on:
  # Manually triggered testing
  workflow_dispatch:

  # Check every PR to main
  pull_request:
    branches:
      - main

jobs:
  docker-test:
    name: Ceedling test:all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build locally
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64
          push: false
          load: true
          tags: tests:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run all Tests using Docker
        run: |
          docker run \
          --interactive \
          --rm \
          --volume ./project-demo:/project \
          tests:${{ github.sha }} \
          ceedling test:all
